version: "3.8"

services:
  database-hangar:
    container_name: space_port_hangar_postgres
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: space_port_db
    ports:
      - "5432:5432"
    volumes:
      - ./space-hangar/src/test/resources:/docker-entrypoint-initdb.d

  database-cantina:
    container_name: space_port_cantina_postgres
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: space_port_db
    ports:
      - "5433:5432"
    volumes:
      - ./space-cantina/src/test/resources:/docker-entrypoint-initdb.d

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
