server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: port
          uri: lb://PORT
          predicates:
            - Path=/**
  main:
    web-application-type: reactive

# Please set spring.main.web-application-type=reactive or remove spring-boot-starter-web dependency.

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Adds trace and span IDs to the Log4J 2
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId},%X{spanId}]"

---

spring:
  config:
    activate:
      on-profile: test
  zipkin:
    enabled: false

eureka:
  client:
    enabled: false
