server:
  port: 8082
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: hangar
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost:5432}/${DATABASE_NAME:space_port_db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

springdoc:
  swagger-ui:
    path: /
