spring:
  application:
    name: hangar

  datasource:
    url: jdbc:postgresql://localhost:5432/space_port_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    path: /

---

spring:
  config:
    activate:
      on-profile: test

eureka:
  client:
    enabled: false
