spring:
  application:
    name: discovery-service
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

# This adds trace and span IDs to the Log4J 2
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId},%X{spanId}]"
