spring:
  application:
    name: port

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  clients:
    hangar:
      name: hangar
      path: /api/v1/spaceships
    cantina:
      name: cantina
      path: /api/v1/pilots

springdoc:
  swagger-ui:
    path: /

---

spring:
  config:
    activate:
      on-profile: test

eureka:
  client:
    enabled: false
