spring:
  application:
    name: port

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  clients:
    hangar:
      name: hangar
      url: /api/v1/spaceships
    cantina:
      name: cantina
      url: /api/v1/pilots

springdoc:
  swagger-ui:
    path: /
