server:
  port: 8083
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: port
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  clients:
    hangar:
      name: hangar
      path: /api/v1/spaceships
    cantina:
      name: cantina
      path: /api/v1/pilots

cors:
  enable:
    api-gateway:
      base-url: http://localhost:8080

springdoc:
  swagger-ui:
    path: /api/docs

# Adds trace and span IDs to the Log4J2
logging:
  pattern:
    level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId},%X{spanId}]"

---

spring:
  config:
    activate:
      on-profile: test
  zipkin:
    enabled: false

eureka:
  client:
    enabled: false
